apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nais-analyse
  name: naisapps-agg-dataproduct
  namespace: nais-analyse
spec:
  image: {{image}}
  schedule: "45 9 * * *"
  gcp:
    bigQueryDatasets:
      - name: apps_aggregated
        permission: READWRITE